### ISSUE TITLE
Install time error throwing

### ISSUE THREAD

**Issue by jestopaul** [jimbobbennett/AnimatedProgress#2]
Could not install package 'JimBobBennett.AnimatedProgress 1.1.0'.
 You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', 
 but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by jimbobbennett** [comment]
The package was built targeting Profile 44, so .NET 4.6. You'll need to either retarget your app to Profile 44 or a compatible profile, or just add the code directly.
